//OV FILE
#define ORGAN_SLOT_BELLY "belly"
#define ORGAN_SLOT_BUTT "butt"

#define DEFAULT_BELLY_SIZE 0
#define MIN_BELLY_SIZE 0
#define MAX_BELLY_SIZE 10

#define BELLY_SIZE_FLAT 0
#define BELLY_SIZE_SMALL 1
#define BELLY_SIZE_MEDIUM 2
#define BELLY_SIZE_LARGE 3
#define BELLY_SIZE_ENORMOUS 4
#define BELLY_SIZE_TOWERING 5
#define BELLY_SIZE_GIGANTIC 6
#define BELLY_SIZE_GARGANTUAN 7
#define BELLY_SIZE_COLOSSAL 8
#define BELLY_SIZE_UNGODLYBIG 9
#define BELLY_SIZE_BAOTHAN 10

#define BELLY_SIZES list(\
	BELLY_SIZE_FLAT,\
	BELLY_SIZE_SMALL,\
	BELLY_SIZE_MEDIUM,\
	BELLY_SIZE_LARGE,\
	BELLY_SIZE_ENORMOUS,\
	BELLY_SIZE_TOWERING,\
	BELLY_SIZE_GIGANTIC,\
	BELLY_SIZE_GARGANTUAN,\
	BELLY_SIZE_COLOSSAL,\
	BELLY_SIZE_UNGODLYBIG,\
	BELLY_SIZE_BAOTHAN,\
)

#define BELLY_SIZES_BY_NAME list(\
	"Flat" = BELLY_SIZE_FLAT, \
	"Small" = BELLY_SIZE_SMALL, \
	"Medium" = BELLY_SIZE_MEDIUM, \
	"Large" = BELLY_SIZE_LARGE, \
	"Enormous" = BELLY_SIZE_ENORMOUS, \
	"Towering" = BELLY_SIZE_TOWERING, \
	"Gigantic" = BELLY_SIZE_GIGANTIC, \
	"Gargantuan" = BELLY_SIZE_GARGANTUAN, \
	"Colossal" = BELLY_SIZE_COLOSSAL, \
	"Ungodly big" = BELLY_SIZE_UNGODLYBIG, \
	"Baothan" = BELLY_SIZE_BAOTHAN, \
)

#define DEFAULT_BUTT_SIZE 0
#define MIN_BUTT_SIZE 0
#define MAX_BUTT_SIZE 8

#define BUTT_SIZE_FLAT 0
#define BUTT_SIZE_SMALL 1
#define BUTT_SIZE_MEDIUM 2
#define BUTT_SIZE_LARGE 3
#define BUTT_SIZE_EXTRALARGE 4
#define BUTT_SIZE_MASSIVE 5
#define BUTT_SIZE_ENORMOUS 6
#define BUTT_SIZE_GIGANTIC 7
#define BUTT_SIZE_GARGANTUAN 8

#define BUTT_SIZES list(\
	BUTT_SIZE_FLAT,\
	BUTT_SIZE_SMALL,\
	BUTT_SIZE_MEDIUM,\
	BUTT_SIZE_LARGE,\
	BUTT_SIZE_EXTRALARGE,\
	BUTT_SIZE_MASSIVE,\
	BUTT_SIZE_ENORMOUS,\
	BUTT_SIZE_GIGANTIC,\
	BUTT_SIZE_GARGANTUAN,\
)

#define BUTT_SIZES_BY_NAME list(\
	"Flat" = BUTT_SIZE_FLAT,\
	"Small" = BUTT_SIZE_SMALL,\
	"Medium" = BUTT_SIZE_MEDIUM,\
	"Large" = BUTT_SIZE_LARGE,\
	"Extra-large" = BUTT_SIZE_EXTRALARGE,\
	"Massive" = BUTT_SIZE_MASSIVE,\
	"Enormous" = BUTT_SIZE_ENORMOUS,\
	"Gigantic" = BUTT_SIZE_GIGANTIC,\
	"Gargantuan" = BUTT_SIZE_GARGANTUAN,\
)
